package com.jpcg.shoppingcart.domain.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.sql.Blob;

/**
 * Represents an Image entity associated with a product in the shopping cart system.
 * Each image is linked to a product and stored as a BLOB (Binary Large Object).
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Image {

    /**
     * The unique identifier of the image.
     * This ID is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the image file (e.g., "product_image.jpg").
     */
    private String fileName;

    /**
     * The type of the image file (e.g., "image/jpeg").
     */
    private String fileType;
    private String url;

    /**
     * The binary data of the image file stored in the database.
     */
    @Lob
    private Blob image;

    /**
     * The product to which this image is associated.
     * Many images can belong to one product.
     */
    @ManyToOne
    @JoinColumn(name = "product_id")
    private Product product;
}
